### ISSUE TITLE
Shader compilation issues on GLES3

### ISSUE THREAD

**Issue by dankcushions** [gonetz/GLideN64#2266]
On RPI4 (ARM32, MESA GLES3):
```GLideN64/src/Graphics/OpenGLContext/GLSL/glsl_CombinerProgramBuilder.cpp:2787: graphics::CombinerProgram* glsl::CombinerProgramBuilder::buildCombinerProgram(Combiner&, Combiner&, const CombinerKey&): Assertion `Utils::checkProgramLinkStatus(program)' failed.```

gliden64.log: https://pastebin.com/PJqiGN6D
```
2020/05/13,01:27:41.189,glsl_Utils.cpp:40,ERROR, "shader_compile error: 0:167(2): error: No precision specified in this scope for type `float'
```
GLES-related precision requirements? i'm not sure if there is anything else meaningful in the log - perhaps it all just bugs out because of this initial issue.

**Comment by dankcushions** [comment]
@joolswills has bisected to this commit: https://github.com/gonetz/GLideN64/commit/a405ad86596d4ec33d84c67400212af3dd3ac236

**Comment by loganmc10** [comment]
@gonetz @standard-two-simplex you just have to declare the floats like "mediump float" or "lowp float", you have to specify a precision for GLES

**Comment by joolswills** [comment]
There were a couple of other errors. Surprised they weren't picked up by whatever shader compiler was used. Different function return definitions

I'm putting the fixes here as I wasn't sure what precision was needed for `address`

```
diff --git a/src/Graphics/OpenGLContext/GLSL/glsl_CombinerProgramBuilder.cpp b/src/Graphics/OpenGLContext/GLSL/glsl_CombinerProgramBuilder.cpp
index b959880..6ae0096 100644
--- a/src/Graphics/OpenGLContext/GLSL/glsl_CombinerProgramBuilder.cpp
+++ b/src/Graphics/OpenGLContext/GLSL/glsl_CombinerProgramBuilder.cpp
@@ -2433,12 +2433,12 @@ public:
 
 			"highp vec2 wrap2D(in highp vec2 tc, in highp float width) \n"
 			"{ \n"
-			"  float address = tc.s + tc.t * width; \n"
+			"  highp float address = tc.s + tc.t * width; \n"
 			"  return vec2(mod(address, width), floor(address/width)); \n"
 			"} \n"
 
 			"uniform mediump vec2 uTexSize0;		\n"
-			"highp vec2[5] textureEngine0(in highp vec2 texCoord) \n"
+			"lowp vec2[5] textureEngine0(in highp vec2 texCoord) \n"
 			"{  \n"
 			"  highp vec2[5] tcData; \n" // {tc00, tc01, tc10, tc11, frPart}
 			"  mediump vec2 intPart = floor(texCoord); \n"
@@ -2453,7 +2453,7 @@ public:
 			"}  \n"
 
 			"uniform mediump vec2 uTexSize1;		\n"
-			"highp vec2[5] textureEngine1(in highp vec2 texCoord) \n"
+			"lowp vec2[5] textureEngine1(in highp vec2 texCoord) \n"
 			"{  \n"
 			"  highp vec2[5] tcData; \n" // {tc00, tc01, tc10, tc11, frPart}
 			"  mediump vec2 intPart = floor(texCoord); \n"
```

**Comment by joolswills** [comment]
textureEngine0 and textureEngine1 were defined as lowp earlier in the code.

**Comment by joolswills** [comment]
The `float address` error was introduced later in commit f5ee3523

**Comment by joolswills** [comment]
The PR https://github.com/gonetz/GLideN64/pull/2265 will either need fixing also or merging and then fixing after (as it adjusts the same `float address` code).

**Comment by gonetz** [comment]
Done: 4974f64a
Please check again.

**Comment by joolswills** [comment]
Confirmed working. Thanks.
