### PR TITLE
Implement N64 depth compare for GLES3.x

### PR DESCRIPTION
**Pull request by fzurita**
I need some guidance here. I attempted to implement N64 depth compare that is compatible with GLES 3.x, but I'm getting stuck on how to handle m_depthImageFBO that the depth image texture attaches to.

Since there are now two depth image textures, one for red and one for green, and we only have 1 depth image FBO. Any idea about what to handle that?

### CODE REVIEW

**Comment by gonetz** [comment]
m_depthImageFBO is used only to fill depth image texture with 1.0, which is analog pf depth buffer clear.
Texture is filled by rendering Rect with given color into it.
It is not probably not the best and surely not the fastest way to fill texture.
If GLES3.x supports glCopyImageSubData, we can rewrite that part with it: make one more image texture, fill it with 1, and copy this texture to textures, which we use for depth compare. In that case we don't need m_depthImageFBO at all.

**Comment by gonetz** [comment]
If glCopyImageSubData is not supported, we still can get rid of m_depthImageFBO. Fillrect uses depth buffer clear if fillrect size is the same as frame buffer size. Otherwise, it uses Rect, which uses shader depth write to fill the depth buffer. As I remember, GLES3 supports depth write. Thus, we can disable depth buffer clear when N64 depth compare enabled and always use depth clear with Rect. It will be acceptable and easy to do fix.

**Comment by gonetz** [comment]
gDPFillRectangle

```
			if (config.generalEmulation.enableFragmentDepthWrite == 0 ||
				(ulx == 0 && uly == 0 && lrx == gDP.scissor.lrx && lry == gDP.scissor.lry)) {
				drawer.clearDepthBuffer(ulx, uly, lrx, lry);
				bBufferCleared = true;
			} else
				depthBufferList().clearBuffer(ulx, uly, lrx, lry);

```
replace by
```
			if (config.frameBufferEmulation.N64DepthCompare == 0 &&
				(config.generalEmulation.enableFragmentDepthWrite == 0 ||
				(ulx == 0 && uly == 0 && lrx == gDP.scissor.lrx && lry == gDP.scissor.lry))) {
				drawer.clearDepthBuffer(ulx, uly, lrx, lry);
				bBufferCleared = true;
			} else
				depthBufferList().clearBuffer(ulx, uly, lrx, lry);

```

and remove m_depthImageFBO usage in DepthBuffer.

**Comment by fzurita** [comment]
Great, I will try that.

**Comment by fzurita** [comment]
Ok, I did as you proposed in your last reply, and I must be doing something wrong. I'm just getting a black screen in Mario 64 and only the 2D elements show up. Can you take a quick look at what I have and make sure it makes sense?

File: src/DepthBuffer.cpp [hunk 1]
```diff
@@ -470,30 +471,6 @@ void DepthBufferList::clearBuffer(u32 _ulx, u32 _uly, u32 _lrx, u32 _lry)
...
-	bindParams.accessMode = textureImageAccessMode::READ_WRITE;
-	bindParams.textureFormat = gfxContext.getFramebufferTextureFormats().depthImageInternalFormat;
-	gfxContext.bindImageTexture(bindParams);
-
-	gfxContext.bindFramebuffer(bufferTarget::DRAW_FRAMEBUFFER, m_pCurrent->m_depthImageFBO);
-
-	const u32 cycleType = gDP.otherMode.cycleType;
-	gDP.otherMode.cycleType = G_CYC_FILL;
-	float color[4] = { 1.0f, 1.0f, 0.0f, 1.0f };
-	dwnd().getDrawer().drawRect(_ulx, _uly, _lrx, _lry, color);
```
Comment (fzurita) [inline src/DepthBuffer.cpp]: I guess I could have two depthImageFBOs and do this twice.

**Comment by fzurita** [comment]
I just tried very similar code to this and it seemed to work fine on the Shield TV. Maybe image texture support in Adreno devices is just buggy. Specially in glsl shaders...

**Comment by fzurita** [comment]
@gonetz Can you take the first 2 commits in this pull request?

**Comment by gonetz** [comment]
> Can you take the first 2 commits in this pull request?

Done

**Comment by gonetz** [comment]
> I just tried very similar code to this and it seemed to work fine on the Shield TV. Maybe image texture support in Adreno devices is just buggy. Specially in glsl shaders...

I built mupen64plus-ae from commit 15ec451aeeb1. It see no issues on my Shield with N64 depth compare enabled. May be it is just not actually enabled?

**Comment by fzurita** [comment]
I logged the generated shaders when n64 depth compare is enabled and it looks like it's on based on that.

**Comment by fzurita** [comment]
@gonetz Please try the latest commit in here: https://github.com/mupen64plus-ae/mupen64plus-ae/commits/gliden64_refactor

Any different?

**Comment by gonetz** [comment]
```
In file included from /home/User/WS/N64/mupen64plus-ae/app/src/main/jni/./mupen64plus-video-gliden64/src/Graphics/OpenGLContext/opengl_ColorBufferReaderWithEGLImage.cpp:5:0:
  /home/User/WS/N64/mupen64plus-ae/app/src/main/jni/./mupen64plus-video-gliden64/src/Graphics/OpenGLContext/opengl_ColorBufferReaderWithEGLImage.h:6:74: fatal error: Graphics/OpenGLContext/GraphicBUfferPrivateApi/GraphicBuffer.h: No such file or directory
   #include <Graphics/OpenGLContext/GraphicBUfferPrivateApi/GraphicBuffer.h>
                                                                            ^
  compilation terminated.
```

**Comment by fzurita** [comment]
In Android Studio, go to Build-->Refresh Linked C++ Projects. Then build again.

**Comment by gonetz** [comment]
I did it twice. No change.

**Comment by fzurita** [comment]
Hmmm, it's building fine here, maybe I forgot to check something in....

**Comment by gonetz** [comment]
<Graphics/OpenGLContext/GraphicBUfferPrivateApi/GraphicBuffer.h>

typo in BUffer

**Comment by fzurita** [comment]
Oh.... you are building in Linux, windows is not case sensitive....

**Comment by gonetz** [comment]
Yes, Linux

**Comment by gonetz** [comment]
```
  In file included from /home/User/WS/N64/mupen64plus-ae/app/src/main/jni/libretro//libretro_custom.c:7:0:
  /home/User/WS/N64/mupen64plus-ae/app/src/main/jni/libretro/RefreshScreen.h:4:23: fatal error: GLES3/gl3.h: No such file or directory
   #include <GLES3/gl3.h>
                         ^
  compilation terminated.
```

**Comment by fzurita** [comment]
Yikes, looks like I made a mistake there. Let me fix that...

**Comment by fzurita** [comment]
Ok, should be fixed if you get the latest version of that branch.

**Comment by gonetz** [comment]
You forgot to fix the typo

**Comment by fzurita** [comment]
Fixed.

**Comment by gonetz** [comment]
> Also, please try the Full-GL mode and GLES 3.0 mode. 

N64 depth compare can't be enabled for GLES 3.0 profile.
GLES 3.1 profile: all 3D graphics missing with N64 depth compare
Full-GL profile: works fine with N64 depth compare. Btw, it has the same issue as desktop version: black lines between polygons when MSAA enabled.

**Comment by fzurita** [comment]
Ok, since my implementation works in the desktop, it should work in GLES 3.1 as well, but it doesn't seem to be.

**Comment by gonetz** [comment]
Hmm, I tested Mario 64 with GLES 3.1, no 3D with N64 depth compare
Zelda works fine with that profile, all graphics is in place

**Comment by fzurita** [comment]
I get only 2D graphics in zelda with the changes I made to the N64 depth compare implementation.

**Comment by gonetz** [comment]
Other games works too for me. The problem is with SM64. This game is particular: it uses depth buffer clear via depth write in shader. I'm not sure that it works on desktop with N64 depth compare enabled.

**Comment by gonetz** [comment]
Desktop version works somehow with SM64 and N64 depth compare, as well as Full-GL profile on Shiled.
There are missing pixels though.

**Comment by gonetz** [comment]
So, GLES 3.1 from your latest commit works ok with N64 depth compare for most games.

**Comment by fzurita** [comment]
Ok, but that's on the shield. My Adreno device has issues with it, but at least I no longer get any shader compilation errors.

**Comment by fzurita** [comment]
I updated this branch, I'm not sure how this pull request was closed.

**Comment by gonetz** [comment]
Bad choice for variables names. Depth1, Depth2, DepthR, DepthG - it is not related to meaning of these objects. Image texture stores Z and delta Z values. Thus: ImageZ, ImageDeltaZ or ImageDz, uImageZ, uImageDz

**Comment by gonetz** [comment]
Two FBO for two depth images: is it the only working way to clear depth buffer image texture?

**Comment by fzurita** [comment]
Since I was only re-implementing the same algorithm without truly understanding it, I didn't have a good basis for the names. I'll give them more appropriate names, like you suggest.

glCopyImageSubData is not guaranteed for GLES 3.1 but it is part of the standard in 3.2. I would rather not have to use that because GLES 3.1 could support this otherwise. I tried the second approach you suggested, but it didn't work quite right, but I suspect it may have been because I was using an Adreno device to test this which doesn't seem to work quite right.

**Comment by fzurita** [comment]
Pull request has been updated. Also, what configuration parameters should be enabled/disabled for N64 depth compare to work correctly?

**Comment by gonetz** [comment]
> what configuration parameters should be enabled/disabled for N64 depth compare to work correctly?

I thought that N64DepthCompare is enough. It was enough until I added render to depth buffer. So, enableFragmentDepthWrite should be on too, I'm not sure that it works when N64DepthCompare is enabled.

**Comment by gonetz** [comment]
I put your work and my fixes to branch https://github.com/gonetz/GLideN64/tree/fix_n64_depth

I found that glMemoryBarrier call is missing in BufferedDrawer and fixed it.
Then I changed depth image texture clear method. It is done via GraphicsDrawer::drawRect call, as I suggested. I tested it on my Shield. GLES 3.1 profile works correctly, with SM64 too. 

N64DepthCompare should not depend on enableFragmentDepthWrite option, but currently depth compare works incorrect without it. I'm trying to find, why.

**Comment by gonetz** [comment]
@fzurita 
I fixed problem with enableFragmentDepthWrite option, it is not necessary anymore for correct work of N64DepthCompare. I tested on Shield, FullGL and GLES 3.1
Please test fix_n64_depth branch on your devices.

**Comment by fzurita** [comment]
Ok, will test.

**Comment by fzurita** [comment]
It didn't fix n64 depth compare for my Adreno device. It almost looks like all 3d geometry is being rendered behind the background. The are no shaver compilation errors or GL errors of any sort.

**Comment by fzurita** [comment]
Everything works fine with my Shield TV device. GLES3, Full GL, with Fragment based depth on/off, as well as in Mario64.

**Comment by gonetz** [comment]
Well, at least we did not break anything. Would be good to find another GLES 3.1 GPU to test, but currently we hardly can do anything more.

**Comment by gonetz** [comment]
Added to refactor_graphics branch.

**Comment by fzurita** [comment]
I have access to a PowerVR and Mali based GLES 3.1 devices

**Comment by fzurita** [comment]
A galaxy s6 with a mali GPU is not too happy with N64 depth compare, see this screenshot. There are no GL errors and it's running at around 4 FPS:

screenshot_20170217-191058

It almost looks like depth information is not being written correctly for all the textures.

**Comment by gonetz** [comment]
I don't think, that performance can be improved: depth compare shader is hard to run efficiently for mobile devices. Graphics issues can be caused by lack of synchronization with writes to image textures. Currently synchronization 
```
	if (config.frameBufferEmulation.N64DepthCompare != 0)
		glMemoryBarrier(GL_SHADER_IMAGE_ACCESS_BARRIER_BIT);

```
called in drawer drawTriangles. Try to add these lines also to drawRects, at the beginning.

**Comment by fzurita** [comment]
I just tried adding that glMemoryBarrier, it didn't help the galaxy s6.

**Comment by gonetz** [comment]
I have no more ideas. At least it works for Shield.

**Comment by fzurita** [comment]
Well, it works with PowerVR, although, at 2 FPS.....

**Comment by gonetz** [comment]
Shield does it fullspeed.

**Comment by fzurita** [comment]
Also, for some reason VertexShaderTexturedTriangle is not compiling for PowerVR, did something change in this shader?

It doesn't like what's after ```if (uFogUsage == 1) {```. It's failing to compile, but with no errors....
