### ISSUE TITLE
Building fails on RPI due to f209304d

### ISSUE THREAD

**Issue by joolswills** [gonetz/GLideN64#2005]
```
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
bcm_host.h found
-- Found ZLIB: /usr/lib/arm-linux-gnueabihf/libz.so (found version "1.2.8") 
-- Found PNG: /usr/lib/arm-linux-gnueabihf/libpng.so (found version "1.6.28") 
-- Found Freetype: /usr/lib/arm-linux-gnueabihf/libfreetype.so (found version "2.6.3") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/RetroPie-Setup/tmp/build/mupen64plus/GLideN64/projects/cmake
Scanning dependencies of target osal
[  1%] Building C object osal/CMakeFiles/osal.dir/osal_files_unix.c.o
[  2%] Linking C static library libosal.a
[  2%] Built target osal
Scanning dependencies of target GLideNHQ
[  3%] Building CXX object GLideNHQ/CMakeFiles/GLideNHQ.dir/TextureFilters_2xsai.cpp.o
[  3%] Building CXX object GLideNHQ/CMakeFiles/GLideNHQ.dir/TextureFilters.cpp.o
[  4%] Building CXX object GLideNHQ/CMakeFiles/GLideNHQ.dir/TextureFilters_hq2x.cpp.o
[  5%] Building CXX object GLideNHQ/CMakeFiles/GLideNHQ.dir/TextureFilters_hq4x.cpp.o
[  6%] Building CXX object GLideNHQ/CMakeFiles/GLideNHQ.dir/TextureFilters_xbrz.cpp.o
[  7%] Building CXX object GLideNHQ/CMakeFiles/GLideNHQ.dir/TxCache.cpp.o
[  7%] Building CXX object GLideNHQ/CMakeFiles/GLideNHQ.dir/TxDbg.cpp.o
[  8%] Building CXX object GLideNHQ/CMakeFiles/GLideNHQ.dir/TxFilter.cpp.o
[  9%] Building CXX object GLideNHQ/CMakeFiles/GLideNHQ.dir/TxFilterExport.cpp.o
[ 10%] Building CXX object GLideNHQ/CMakeFiles/GLideNHQ.dir/TxHiResCache.cpp.o
[ 11%] Building CXX object GLideNHQ/CMakeFiles/GLideNHQ.dir/TxImage.cpp.o
[ 12%] Building CXX object GLideNHQ/CMakeFiles/GLideNHQ.dir/TxQuantize.cpp.o
[ 13%] Building CXX object GLideNHQ/CMakeFiles/GLideNHQ.dir/TxReSample.cpp.o
[ 13%] Building CXX object GLideNHQ/CMakeFiles/GLideNHQ.dir/TxTexCache.cpp.o
[ 14%] Building CXX object GLideNHQ/CMakeFiles/GLideNHQ.dir/TxUtil.cpp.o
[ 15%] Linking CXX static library libGLideNHQ.a
[ 15%] Built target GLideNHQ
Scanning dependencies of target mupen64plus-video-GLideN64
[ 16%] Building CXX object CMakeFiles/mupen64plus-video-GLideN64.dir/CombinerKey.cpp.o
[ 17%] Building CXX object CMakeFiles/mupen64plus-video-GLideN64.dir/Combiner.cpp.o
[ 18%] Building CXX object CMakeFiles/mupen64plus-video-GLideN64.dir/CommonPluginAPI.cpp.o
[ 18%] Building CXX object CMakeFiles/mupen64plus-video-GLideN64.dir/Config.cpp.o
[ 19%] Building CXX object CMakeFiles/mupen64plus-video-GLideN64.dir/convert.cpp.o
[ 20%] Building CXX object CMakeFiles/mupen64plus-video-GLideN64.dir/DebugDump.cpp.o
[ 21%] Building CXX object CMakeFiles/mupen64plus-video-GLideN64.dir/Debugger.cpp.o
[ 22%] Building CXX object CMakeFiles/mupen64plus-video-GLideN64.dir/DepthBuffer.cpp.o
[ 23%] Building CXX object CMakeFiles/mupen64plus-video-GLideN64.dir/DisplayWindow.cpp.o
[ 24%] Building CXX object CMakeFiles/mupen64plus-video-GLideN64.dir/DisplayLoadProgress.cpp.o
[ 24%] Building CXX object CMakeFiles/mupen64plus-video-GLideN64.dir/FrameBuffer.cpp.o
[ 25%] Building CXX object CMakeFiles/mupen64plus-video-GLideN64.dir/FrameBufferInfo.cpp.o
[ 26%] Building CXX object CMakeFiles/mupen64plus-video-GLideN64.dir/GBI.cpp.o
[ 27%] Building CXX object CMakeFiles/mupen64plus-video-GLideN64.dir/gDP.cpp.o
[ 28%] Building CXX object CMakeFiles/mupen64plus-video-GLideN64.dir/GLideN64.cpp.o
[ 29%] Building CXX object CMakeFiles/mupen64plus-video-GLideN64.dir/GraphicsDrawer.cpp.o
[ 29%] Building CXX object CMakeFiles/mupen64plus-video-GLideN64.dir/gSP.cpp.o
[ 30%] Building CXX object CMakeFiles/mupen64plus-video-GLideN64.dir/Keys.cpp.o
[ 31%] Building CXX object CMakeFiles/mupen64plus-video-GLideN64.dir/Log.cpp.o
[ 32%] Building CXX object CMakeFiles/mupen64plus-video-GLideN64.dir/N64.cpp.o
[ 33%] Building CXX object CMakeFiles/mupen64plus-video-GLideN64.dir/NoiseTexture.cpp.o
[ 34%] Building CXX object CMakeFiles/mupen64plus-video-GLideN64.dir/PaletteTexture.cpp.o
[ 35%] Building CXX object CMakeFiles/mupen64plus-video-GLideN64.dir/Performance.cpp.o
[ 35%] Building CXX object CMakeFiles/mupen64plus-video-GLideN64.dir/PostProcessor.cpp.o
[ 36%] Building CXX object CMakeFiles/mupen64plus-video-GLideN64.dir/RDP.cpp.o
[ 37%] Building CXX object CMakeFiles/mupen64plus-video-GLideN64.dir/RSP.cpp.o
[ 38%] Building CXX object CMakeFiles/mupen64plus-video-GLideN64.dir/SoftwareRender.cpp.o
[ 39%] Building CXX object CMakeFiles/mupen64plus-video-GLideN64.dir/TexrectDrawer.cpp.o
[ 40%] Building CXX object CMakeFiles/mupen64plus-video-GLideN64.dir/TextDrawer.cpp.o
[ 40%] Building CXX object CMakeFiles/mupen64plus-video-GLideN64.dir/TextureFilterHandler.cpp.o
[ 41%] Building CXX object CMakeFiles/mupen64plus-video-GLideN64.dir/Textures.cpp.o
[ 42%] Building CXX object CMakeFiles/mupen64plus-video-GLideN64.dir/VI.cpp.o
[ 43%] Building CXX object CMakeFiles/mupen64plus-video-GLideN64.dir/ZlutTexture.cpp.o
[ 44%] Building CXX object CMakeFiles/mupen64plus-video-GLideN64.dir/BufferCopy/ColorBufferToRDRAM.cpp.o
[ 45%] Building CXX object CMakeFiles/mupen64plus-video-GLideN64.dir/BufferCopy/DepthBufferToRDRAM.cpp.o
[ 46%] Building CXX object CMakeFiles/mupen64plus-video-GLideN64.dir/BufferCopy/RDRAMtoColorBuffer.cpp.o
[ 46%] Building CXX object CMakeFiles/mupen64plus-video-GLideN64.dir/DepthBufferRender/ClipPolygon.cpp.o
[ 47%] Building CXX object CMakeFiles/mupen64plus-video-GLideN64.dir/DepthBufferRender/DepthBufferRender.cpp.o
[ 48%] Building CXX object CMakeFiles/mupen64plus-video-GLideN64.dir/common/CommonAPIImpl_common.cpp.o
[ 49%] Building CXX object CMakeFiles/mupen64plus-video-GLideN64.dir/Graphics/Context.cpp.o
[ 50%] Building CXX object CMakeFiles/mupen64plus-video-GLideN64.dir/Graphics/ColorBufferReader.cpp.o
[ 51%] Building CXX object CMakeFiles/mupen64plus-video-GLideN64.dir/Graphics/CombinerProgram.cpp.o
[ 52%] Building CXX object CMakeFiles/mupen64plus-video-GLideN64.dir/Graphics/ObjectHandle.cpp.o
[ 52%] Building CXX object CMakeFiles/mupen64plus-video-GLideN64.dir/Graphics/OpenGLContext/GLFunctions.cpp.o
[ 53%] Building CXX object CMakeFiles/mupen64plus-video-GLideN64.dir/Graphics/OpenGLContext/opengl_Attributes.cpp.o
/home/pi/RetroPie-Setup/tmp/build/mupen64plus/GLideN64/src/Graphics/OpenGLContext/GLFunctions.cpp: In function ‘void initGLFunctions()’:
/home/pi/RetroPie-Setup/tmp/build/mupen64plus/GLideN64/src/Graphics/OpenGLContext/GLFunctions.cpp:10:47: error: ‘g_eglGetNativeClientBufferANDROID’ was not declared in this scope
 #define GL_GET_PROC_ADR(proc_type, proc_name) g_##proc_name = (proc_type) dlsym(gles2so, #proc_name);
                                               ^
/home/pi/RetroPie-Setup/tmp/build/mupen64plus/GLideN64/src/Graphics/OpenGLContext/GLFunctions.cpp:245:2: note: in expansion of macro ‘GL_GET_PROC_ADR’
  GL_GET_PROC_ADR(PFNEGLGETNATIVECLIENTBUFFERANDROIDPROC, eglGetNativeClientBufferANDROID);
  ^~~~~~~~~~~~~~~
/home/pi/RetroPie-Setup/tmp/build/mupen64plus/GLideN64/src/Graphics/OpenGLContext/GLFunctions.cpp:245:18: error: ‘PFNEGLGETNATIVECLIENTBUFFERANDROIDPROC’ was not declared in this scope
  GL_GET_PROC_ADR(PFNEGLGETNATIVECLIENTBUFFERANDROIDPROC, eglGetNativeClientBufferANDROID);
                  ^
/home/pi/RetroPie-Setup/tmp/build/mupen64plus/GLideN64/src/Graphics/OpenGLContext/GLFunctions.cpp:10:64: note: in definition of macro ‘GL_GET_PROC_ADR’
 #define GL_GET_PROC_ADR(proc_type, proc_name) g_##proc_name = (proc_type) dlsym(gles2so, #proc_name);
                                                                ^~~~~~~~~
CMakeFiles/mupen64plus-video-GLideN64.dir/build.make:1094: recipe for target 'CMakeFiles/mupen64plus-video-GLideN64.dir/Graphics/OpenGLContext/GLFunctions.cpp.o' failed
make[2]: *** [CMakeFiles/mupen64plus-video-GLideN64.dir/Graphics/OpenGLContext/GLFunctions.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:68: recipe for target 'CMakeFiles/mupen64plus-video-GLideN64.dir/all' failed
make[1]: *** [CMakeFiles/mupen64plus-video-GLideN64.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

looks like this was introduced with f209304d0b052dd53fcaadfa9f21055ab9f489d5

```
commit f209304d0b052dd53fcaadfa9f21055ab9f489d5
Author: fzurita <fzurita@gmail.com>
Date:   Sun Feb 3 22:00:29 2019 -0500

    Add support for Android EGL Image Public API
```

**Comment by gonetz** [comment]
@fzurita please check it.
@joolswills Can you fix these errors? I don't have RPI or cross-platform compile setup for RPI, so I don't want to do it blindly.

**Comment by joolswills** [comment]
Probably. I think maybe just misses some ifdefs to wrap the failing parts as they are Android only? I'm short on time but will look when I can if (I it's not resolved before).

**Comment by joolswills** [comment]
Will add comment to PR for author of changes.

**Comment by joolswills** [comment]
Had a quick look -

```diff
+++ b/src/Graphics/OpenGLContext/GLFunctions.cpp
@@ -242,8 +242,10 @@ void initGLFunctions()
        GL_GET_PROC_ADR(PFNGLBLENDCOLORPROC, glBlendColor);
        GL_GET_PROC_ADR(PFNGLREADBUFFERPROC, glReadBuffer);
        GL_GET_PROC_ADR(PFNGLFINISHPROC, glFinish);
+#if defined(OS_ANDROID)
        GL_GET_PROC_ADR(PFNEGLGETNATIVECLIENTBUFFERANDROIDPROC, eglGetNativeClientBufferANDROID);
 #endif
+#endif
 
        GL_GET_PROC_ADR(PFNGLCREATESHADERPROC, glCreateShader);
        GL_GET_PROC_ADR(PFNGLCOMPILESHADERPROC, glCompileShader);
diff --git a/src/Graphics/OpenGLContext/opengl_ColorBufferReaderWithEGLImage.h b/src/Graphics/OpenGLContext/opengl_ColorBufferReaderWithEGLImage.h
index 0b9118d3..2ff90d76 100644
--- a/src/Graphics/OpenGLContext/opengl_ColorBufferReaderWithEGLImage.h
+++ b/src/Graphics/OpenGLContext/opengl_ColorBufferReaderWithEGLImage.h
@@ -4,7 +4,9 @@
 #include <Graphics/OpenGLContext/GraphicBuffer/GraphicBufferWrapper.h>
 #include "opengl_CachedFunctions.h"
 
+#if defined(OS_ANDROID)
 #include <android/hardware_buffer.h>
+#endif
 
 namespace opengl {
 ```

is needed at least, but then more failures

```
Scanning dependencies of target mupen64plus-video-GLideN64
[ 16%] Building CXX object CMakeFiles/mupen64plus-video-GLideN64.dir/Graphics/OpenGLContext/opengl_BufferManipulationObjectFactory.cpp.o
[ 17%] Building CXX object CMakeFiles/mupen64plus-video-GLideN64.dir/Graphics/OpenGLContext/opengl_ContextImpl.cpp.o
In file included from /home/pi/RetroPie-Setup/tmp/build/mupen64plus/GLideN64/src/Graphics/OpenGLContext/opengl_ColorBufferReaderWithEGLImage.h:4:0,
                 from /home/pi/RetroPie-Setup/tmp/build/mupen64plus/GLideN64/src/Graphics/OpenGLContext/opengl_ContextImpl.cpp:10:
/home/pi/RetroPie-Setup/tmp/build/mupen64plus/GLideN64/src/./Graphics/OpenGLContext/GraphicBuffer/GraphicBufferWrapper.h:4:37: fatal error: android/hardware_buffer.h: No such file or directory
 #include <android/hardware_buffer.h>
                                     ^
compilation terminated.
CMakeFiles/mupen64plus-video-GLideN64.dir/build.make:1286: recipe for target 'CMakeFiles/mupen64plus-video-GLideN64.dir/Graphics/OpenGLContext/opengl_ContextImpl.cpp.o' failed
make[2]: *** [CMakeFiles/mupen64plus-video-GLideN64.dir/Graphics/OpenGLContext/opengl_ContextImpl.cpp.o] Error 1
CMakeFiles/Makefile2:68: recipe for target 'CMakeFiles/mupen64plus-video-GLideN64.dir/all' failed
make[1]: *** [CMakeFiles/mupen64plus-video-GLideN64.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

is GraphicBufferWrapper.cpp needed outside of android ? Looks like it has android specific code in it, but then src/Graphics/OpenGLContext/GraphicBuffer/GraphicBufferWrapper.h is referenced from other sources. Hopefully this helps, but I think the author is likely to have a better idea.

**Comment by fzurita** [comment]
GraphicBuffer is not used outside of Android. And yes, it seems like I missed a few ```#ifdef OS_ANDROID```

**Comment by fzurita** [comment]
To fix, please replace 
```
#include "opengl_ColorBufferReaderWithEGLImage.h"
```

with
```
#ifdef OS_ANDROID
#include "opengl_ColorBufferReaderWithEGLImage.h"
#endif
```

**Comment by fzurita** [comment]
I can make a pull request, but I don't know if it will fix all the errors since I don't have an easy way to verify it.
