### ISSUE TITLE
GLES2 Shader Issues caused by a405ad86

### ISSUE THREAD

**Issue by m4xw** [gonetz/GLideN64#2271]
Offending commit: https://github.com/gonetz/GLideN64/commit/a405ad86596d4ec33d84c67400212af3dd3ac236
cc @standard-two-simplex 
```
2020/05/15,23:00:53.482,opengl_GLInfo.cpp:46,VERBOSE, "OpenGL ES major version: 2"
2020/05/15,23:00:53.482,opengl_GLInfo.cpp:47,VERBOSE, "OpenGL ES minor version: 0"
2020/05/15,23:00:53.482,opengl_GLInfo.cpp:50,VERBOSE, "OpenGL vendor: Apple Inc."
2020/05/15,23:00:53.482,opengl_GLInfo.cpp:68,VERBOSE, "OpenGL renderer: Apple A12 GPU"
2020/05/15,23:00:53.486,glsl_Utils.cpp:39,ERROR, "shader_compile error: ERROR: 0:47: 'tcData0' : syntax error: Array size must appear after variable name
```
That's not valid GLSL

![grafik](https://user-images.githubusercontent.com/13141469/82097876-110dc580-9704-11ea-921f-86c3044255a9.png)

**Comment by m4xw** [comment]
On top of just invalid syntax, IOS babyrages about ```
highp vec2 tcData0[5];    
highp vec2[5] textureEngine0(in highp vec2 texCoord);    
highp vec2[5] textureEngine1(in highp vec2 texCoord);    
tcData0 = textureEngine0(vTexCoord0); ```
Fix is to move the return to a out param.

**Comment by m4xw** [comment]
Also more issues, after this is fixed, seems unrelated to the offending commit tho.
![grafik](https://user-images.githubusercontent.com/13141469/82102078-a7df7f80-970e-11ea-95dc-4eadf200bec3.png)

**Comment by standard-two-simplex** [comment]
Function `TextureMipMap()` was introduced in commit bb2221d55f5a2f59ae28b42abdfd329487297c00

I can see a missing `m_ part =` just before `TextureMipMap()` declaration. Also, further strings should have `m_part +=` instead of `m_part =` in order not to delete previous data.

@m4xw Try this fixes and report back please.

**Comment by m4xw** [comment]
I will give it a shot, just woke up and feel pretty done so not sure if I get to it today, so tomorrow or monday at worst.

**Comment by gonetz** [comment]
It should be fixed now: 4f58d66e
