### ISSUE TITLE
Nexus 6p fragment shader compilation error

### ISSUE THREAD

**Issue by fzurita** [gonetz/GLideN64#895]
Shaders fail to compile in the OpenGL ES (2.0, 3.0, and 3.1) version of the plugin on a Nexus 6p phone. The nexus 6p has an Adreno 430 GPU running driver release V127. Here is an example shader that fails to compile:

```
#version 310 es 
uniform sampler2D uTex0;		
uniform sampler2D uTex1;		
uniform lowp sampler2DMS uMSTex0;	
uniform lowp sampler2DMS uMSTex1;	
uniform lowp ivec2 uMSTexEnabled;	
layout (std140) uniform ColorsBlock {
  lowp vec4 uFogColor;			
  lowp vec4 uCenterColor;		
  lowp vec4 uScaleColor;		
  lowp vec4 uBlendColor;		
  lowp vec4 uEnvColor;			
  lowp vec4 uPrimColor;		
  lowp float uPrimLod;			
  lowp float uK4;				
  lowp float uK5;				
};								
uniform mediump vec2 uScreenScale;	
uniform lowp int uAlphaCompareMode;	
uniform lowp int uAlphaDitherMode;	
uniform lowp int uColorDitherMode;	
uniform lowp int uFogUsage;	
uniform lowp ivec2 uFbMonochrome;		
uniform lowp ivec2 uFbFixedAlpha;
uniform lowp int uSpecialBlendMode;
uniform lowp int uEnableAlphaTest;	
uniform lowp float uAlphaTestValue;
uniform mediump vec2 uDepthScale;	
in lowp vec4 vShadeColor;	
in mediump vec2 vTexCoord0;
in mediump vec2 vTexCoord1;
in mediump vec2 vLodTexCoord;
in lowp float vNumLights;	
in mediump float vFogFragCoord;
lowp vec3 input_color;			
out lowp vec4 fragColor;		
															
lowp float snoise();						
void calc_light(in lowp float fLights, in lowp vec3 input_color, out lowp vec3 output_color);
mediump float mipmap(out lowp vec4 readtex0, out lowp vec4 readtex1);		
lowp vec4 readTex(in sampler2D tex, in mediump vec2 texCoord, in lowp int fbMonochrome, in bool fbFixedAlpha);	
lowp vec4 readTexMS(in lowp sampler2DMS mstex, in mediump vec2 texCoord, in lowp int fbMonochrome, in bool fbFixedAlpha);	
bool depth_compare();										
void colorNoiseDither(in lowp float _noise, inout lowp vec3 _color);	
void alphaNoiseDither(in lowp float _noise, inout lowp float _alpha);
									
void main()						
{									
#ifdef GL_NV_fragdepth			
  gl_FragDepth = clamp((gl_FragCoord.z * 2.0 - 1.0) * uDepthScale.s + uDepthScale.t, 0.0, 1.0);   
#endif										
  lowp vec4 vec_color, combined_color;	
  lowp float alpha1, alpha2;			
  lowp vec3 color1, color2;				
  lowp vec4 readtex0 = readTex(uTex0, vTexCoord0, uFbMonochrome[0], uFbFixedAlpha[0] != 0); 
  input_color = vShadeColor.rgb;
  vec_color = vec4(input_color, vShadeColor.a); 
  alpha1 = (readtex0.a )*uPrimColor.a; 
  if (uEnableAlphaTest != 0) {				
    lowp float alphaTestValue = (uAlphaCompareMode == 3 && alpha1 > 0.0) ? snoise() : uAlphaTestValue;	
    if  (alpha1 < alphaTestValue) discard;	
  }										
  color1 = (uPrimColor.rgb ); 
  if (uSpecialBlendMode == 1)													
		color1 = color1 * alpha1 + uBlendColor.rgb * (1.0 - alpha1);			
  else if (uSpecialBlendMode == 2)												
		color1 = uBlendColor.rgb * uFogColor.a + color1 * (1.0 - uFogColor.a);	
  else if (uSpecialBlendMode == 3)												
		color1 = color1 * uFogColor.a + uFogColor.rgb * (1.0 - uFogColor.a);	
  combined_color = vec4(color1, alpha1); 
  alpha2 = alpha1; 
  color2 = color1; 
  if (uColorDitherMode == 2) colorNoiseDither(snoise(), color2);	
  if (uAlphaDitherMode == 2) alphaNoiseDither(snoise(), alpha2);	
  lowp int fogUsage = uFogUsage;			
  if (fogUsage >= 256) fogUsage -= 256;	
  if (fogUsage == 2) fragColor = vec4(color2, uFogColor.a);				
  else if (fogUsage == 3) fragColor = uFogColor;							
  else if (fogUsage == 4) fragColor = vec4(color2, uFogColor.a*alpha2);	
  else fragColor = vec4(color2, alpha2);									
  if (uFogUsage == 257) 
    fragColor.rgb = mix(fragColor.rgb, uFogColor.rgb, vFogFragCoord); 
}                               

lowp vec4 readTex(in sampler2D tex, in mediump vec2 texCoord, in lowp int fbMonochrome, in bool fbFixedAlpha)	
{												
  lowp vec4 texColor = texture(tex, texCoord);	
  if (fbMonochrome == 1) texColor = vec4(texColor.r);	
  else if (fbMonochrome == 2) 						
    texColor.rgb = vec3(dot(vec3(0.2126, 0.7152, 0.0722), texColor.rgb));	
  if (fbFixedAlpha) texColor.a = 0.825;		
  return texColor;								
}												

uniform sampler2D uTexNoise;		
lowp float snoise()									
{														
  ivec2 coord = ivec2(gl_FragCoord.xy/uScreenScale);	
  return texelFetch(uTexNoise, coord, 0).r;			
}														

void colorNoiseDither(in lowp float _noise, inout lowp vec3 _color)	
{															
    mediump vec3 tmpColor = _color*255.0;					
    mediump ivec3 iColor = ivec3(tmpColor);				
    iColor |= ivec3(tmpColor*_noise)&7;					
    _color = vec3(iColor)/255.0;							
}															
void alphaNoiseDither(in lowp float _noise, inout lowp float _alpha)	
{															
    mediump float tmpAlpha = _alpha*255.0;					
    mediump int iAlpha = int(tmpAlpha);					
    iAlpha |= int(tmpAlpha*_noise)&7;						
    _alpha = float(iAlpha)/255.0;							
}															


```

**Comment by fzurita** [comment]
Another note, ```glGetShaderInfoLog``` is very unhelpful since it just returns an empty string.

**Comment by gonetz** [comment]
I'm afraid, I can't help here. I don't have that device and I can't do right guess  without information from glGetShaderInfoLog. Try to simplify generated shader as much as possible.

**Comment by fzurita** [comment]
Yeah, it's hard for me too since I don't have the device either. I'm helping someone with the device troubleshoot the issue. I'm downloading the Qualcomm developer SDK. I'm hoping that it has some way to verify a fragment shader.

**Comment by fzurita** [comment]
@gonetz , Ok, I think I made some progress with the tester's help. I was able to get the 3.0 variant working with the newer Adreno drivers. Please see the changes I have made in this branch. For some reason it's still not working with the 3.1 variant though.

https://github.com/mupen64plus-ae/mupen64plus-ae/commits/test_nexus6p_fix

**Comment by gonetz** [comment]
I've checked your commits.
Changes before "video-gliden64: more test fixes for nexus 6p this time focused on OpenGL" are good and should be in GLideN64 master. Could you make them as a pull request?

The code regarding multisampling is questionable. Multisampling does not work on my Shield tablet, but I don't have shader compilation errors either. If other compilers complain about the "sampler2DMS", it probably the reason. Need to find, which ms sampler type is correct for GLES 3.1

**Comment by fzurita** [comment]
Yeah, I'll make them as a pull request when I get a chance.

**Comment by fzurita** [comment]
This is getting interesting, if multisampling is disabled,  I changed the code so that there are no instances of any variables of the type sampler2DMS. It still failed to compile even though the code should be identical to the 3.0 generated GLSL code. There must be some differences. I have the generated GLSL, it will be interesting to see how it is different when I get a chance.

**Comment by gonetz** [comment]
According to GLES 3.1 specification, sampler2DMS is the only valid GLSL keyword for TEXTURE_2D_-
MULTISAMPLE texture:
https://www.khronos.org/registry/gles/specs/3.1/es_spec_3.1.pdf

How exactly GLSL compilers complain about the "sampler2DMS"?

**Comment by fzurita** [comment]
I think it was complaining because there compiler I was using was for #version 300 instead of 310

**Comment by fzurita** [comment]
FYI, in my NVidia shield TV, multisampling works correctly as long as frame buffer emulation is disabled.

**Comment by gonetz** [comment]
Yes, the problem is with multisampled FBO textures

**Comment by fzurita** [comment]
I'm not exactly sure what is wrong with the 3.1 version in the nexus 6p. I have compared the generated GLSL source and there practically no difference after my changes, yet it still fails to compile...

**Comment by fzurita** [comment]
@gonetz This another Adreno issue.

**Comment by fzurita** [comment]
Ok, I made some headway into this. I upgraded my phone to a ZTE Axon 7 and I have the same issue.

It turns out that work GLSL version 310, Adreno doesn't like for the Sampler2D type to be used as an argument to a function. This is being done in the ```readTex``` GLSL function.

I was able to get around the issue by performing the texture lookup outside the function and pushing in the resulting vec4 but only for the standard texture filtering. For the 3-point filtering this is much harder because we do a lot more texture lookups.

**Comment by gonetz** [comment]
> Adreno doesn't like for the Sampler2D type to be used as an argument to a function

:(

**Comment by fzurita** [comment]
I'm trying to come up with an implementation that doesn't use the Sampler2D as an argument or some sort of workaround,

**Comment by fzurita** [comment]
Ok, I think there is way to do it while passing an I'd to the texture being used using this extension:

EXT_gpu_shader5

But this extension only works in GLSL version 310.

**Comment by gonetz** [comment]
Ok, good luck!
I wonder, which manipulations with Sampler2D type Adreno supports?
Can we create a Sampler2D variable and assign value from uTex0 or uTex1 uniforms to it?

**Comment by fzurita** [comment]
I tried, it wouldn't compile.

**Comment by fzurita** [comment]
Ok, I think I have a good fix. I replaced both readTex implementations with macro definitions and that works since it's done during preprocessing.

I'll submit s pull request soon. I have to makes sure it works with other devices as well, I read that new line characters in macro definitions are not guaranteed to work.

**Comment by fzurita** [comment]
After doing all these changes, it seems that Multisampling started working with Adreno with GLES 3.1, but there are some weird issues. See here:
![super_mario_64-000](https://cloud.githubusercontent.com/assets/11581687/19226746/7531f8b2-8e7d-11e6-86bf-0a3973209f20.png)
